# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterFly' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TwitterFly
  
  pod 'OhhAuth'
  pod 'SDWebImage', '~> 4.0'
  

  target 'TwitterFlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterFlyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
